### ISSUE TITLE
Function "correctTaxo" doesn't work

### ISSUE THREAD

**Issue by NicoLabriere** [umr-amap/BIOMASS#19]
Probably related to an issue with http://taxosaurus.org

Here is the message I get when I try to run the function:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [taxosaurus.org] Connection timed out after 10001 milliseconds

Thanks for looking into this!

**Comment by MaximeRM** [comment]
Thanks Nicolas. Yes, the taxosaurus server on which this function relies is down for at least one week now. I am currently trying to know more about this and hope that it will be fixed soon as we are not the only ones to rely on it!

Best

Maxime

**Comment by AragonAmazon** [comment]
Thanks god! I was getting crazy trying to solve that problem. Do you have any update when it will be up. Thank you for a wonderful program!
