### ISSUE TITLE
Package "Terra"

### ISSUE THREAD

**Issue by AbhorWrent** [umr-amap/BIOMASS#35]
I've been trying to set up and run the biomass program in R Studio, but I'm unable to get anything started because there is no package called "terra". It doesn't appear to be a part of the biomass package, but it also isn't available for installation from CRAN. Below is a screenshot of the error message I get. Granted, I'm very new to using R so this may not be a bug so much as user error, but any help would be appreciated. 

![image](https://github.com/umr-amap/BIOMASS/assets/46789480/e4b98c4e-1097-45c1-a65a-18c1fd8b663d)

**Comment by lamonica-d** [comment]
Hi,

Sorry for the late reply, we were working to put BIOMASS back on CRAN (it has been archived in June). 

The latest version of BIOMASS 2.1.9 is now available on CRAN https://cran.r-project.org/web/packages/BIOMASS/index.html so you can install it from install.packages() function directly without going though the Github repo.
This version does not depend on terra package, so you can try to install it again using 
> install.packages("BIOMASS")

Dominique
