### ISSUE TITLE
Failed to connect to tnrs service

### ISSUE THREAD

**Issue by laura-simoes** [umr-amap/BIOMASS#36]
I am experiencing this error with correctTaxo() for 2 days: 

Error in FUN(X[[i]], ...) : 
  Bad Request (HTTP 400). Failed to connect to tnrs service. Retry maybe later.

**Comment by JonathanVSV** [comment]
Just ran `correctTaxo()` today and had exactly the same issue.

**Comment by MaximeRM** [comment]
Thank you for pointing out this issue. We will work on it asap!
Sorry for the inconvenience.

**Comment by JonathanVSV** [comment]
Based on the following script: [TNRSapi example](https://github.com/ojalaquellueva/TNRSapi/blob/master/tnrs_api_example.R), it seems like changing `class = jsonlite::unbox("wfo")` inside the `correctTaxo` avoids the error.

**Comment by MaximeRM** [comment]
Hi Jonathan,

We got yesterday the same conclusions as yours. This is now fixed in the github version and I will submit the corrected version to CRAN today.

Best

**Comment by laura-simoes** [comment]
Thank you for fixing it!
