### ISSUE TITLE
Problem with correctTaxo

### ISSUE THREAD

**Issue by FabioMostacato** [umr-amap/BIOMASS#37]
Hello, Dr. MaximeRM. 1st i thank you (et al. ) for this very cool package. I am using R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045).

I am having trouble with Taxo<- correctTaxo(genus = jub$Genus, species = jub$Species). It answers with Using useCache=TRUE is recommended to reduce online search time for the next research
| | 0%Error in FUN(X[[i]], ...) :
Bad Request (HTTP 400). Failed to connect to tnrs service. Retry maybe later.

I tried useCache= T but it doesn' work either.

I installed Biomass with remotes::install_github("cran/BIOMASS"). This R version is not accepting the usual way of installation (install.packages()).

Anyway, i did the analysis without correctTaxo.

Best Regards.

**Comment by billy34** [comment]
Hello cran version is still outdated and needs an update (fortunately soon as most of the work is done :-)
To install the latest version (which correct the access to TNRS) you must use the following command
```
remotes::install_github("umr-amap/BIOMASS")
```
and not `remotes::install_github("cran/BIOMASS")` as you apparently used.

I tested the access to TNRS and it works (at least on my computer). Please come back if it is not the case after the correct install

**Comment by FabioMostacato** [comment]
Thanks for the support.

However, i tried to install BIOMASS through "remotes::install_github("umr-amap/BIOMASS")" before report the problem here. I did it again just to confirm the feedback i had previously:

> remotes::install_github("umr-amap/BIOMASS")
Downloading GitHub repo umr-amap/BIOMASS@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/umr-amap/BIOMASS/tarball/HEAD' failed

Given that i used "remotes::install_github("cran/BIOMASS")". It worked, but i had problem with correctTaxo. But this was the least problem.

Fabio

**Comment by billy34** [comment]
Just checking obvious culprits :-)

Can you check the version of `BIOMASS` that is installed ?
```
installed.packages()["BIOMASS", "Version"]
```
Should report at least version **2.1.9**.

I tried the install from an empty VM and was able to access the repository, strange.

Can you try to install a well-known package (such as `rlang`) from it's github ?
```
remotes::install_github("r-lib/rlang")
```
If this work then we have a problem with our repository otherwise its on your side :-)

You can also try this alternate way that use base R install functions.
```
install.packages('BIOMASS', repos = c('https://umr-amap.r-universe.dev', 'https://cloud.r-project.org'))
```

Hope this helps
Guillaume

**Comment by FabioMostacato** [comment]
Hello, Mr. Guillaume.

I followed your instructions:

installed.packages()["BIOMASS", "Version"]: "2.1.8"

remotes::install_github("r-lib/rlang"): * DONE (rlang)      ---      It worked.

Still no culprits? This problem is getting interesting.

Fabio

**Comment by FabioMostacato** [comment]
Hello, again.

I didn't care at first to be true.

However, now correctTaxo worked!

Anyway, i have no clue on the cause of this problem. I would appreciate if you clarify it.

Thanks.

Fabio

**Comment by billy34** [comment]
Glad to hear that it worked. 
We will investigate and try at least to reproduce the problem.
Happy use of BIOMASS !

**Comment by FabioMostacato** [comment]
Great to hear that.

If i could help, let me know.

Take care!

**Comment by lamonica-d** [comment]
Hi Fabio,

Actually there was issues with TNRS service website in the past weeks, that might be the origin of the issue with correctTaxo. 

FYI the last version of BIOMASS 2.1.9 is now available on CRAN https://cran.r-project.org/web/packages/BIOMASS/index.html so you can install it from install.packages() function directly without going though the Github repo.

Have a nice day !
Dominique

**Comment by FabioMostacato** [comment]
Hello.

We should always include it as a possible culprit!

Take care.

Fabio
