### ISSUE TITLE
predictHeight() is a missing function in the BIOMASS package

### ISSUE THREAD

**Issue by mlouwzoo** [umr-amap/BIOMASS#38]
Good day, 
Thank you for making such an awesome package!

I am using R Version: R version 4.2.3 (2023-03-15)
And  RStudio Version: 1.2.1335.

I use a macOS High Sierra Version 10.13.6 on a MacBook Pro.

I struggled to download the BIOMASS package but somehow I managed (I didn't record the details unfortunately. I think I said "no" when it asked to install it from source. I tried various options and it eventually worked). 

I have used modelHD() to get model describing the D:H relationship of my data. Now I want to use predictHeight() to get height values for all my stems with D data. 

However, I get the following error:
Error in predictHeight(D, m1, err = FALSE, plot = NULL) : 
  could not find function "predictHeight"

Any assistance would be much appreciated!

**Comment by billy34** [comment]
Hello,
The predictHeight function was not exported. It is now fixed but will not be on CRAN soon.
In the meantime you can use the version on github by running the following command
`remotes::install_github("umr-amap/BIOMASS")`
Sorry for that
