### ISSUE TITLE
correctTaxo 

### ISSUE THREAD

**Issue by ArthurBailly** [umr-amap/BIOMASS#42]
The correctTaxo function is running without ending.
The problem seems to come from the httr2::req_perform(req) on line 118

**Comment by ArthurBailly** [comment]
EDIT : 
The function TNRS, from the TNRS R package, has the same problem, with the following message when manually interrupting the function : "There appears to be a problem reaching the API."

**Comment by billy34** [comment]
It does not seems to work either from the online form (https://tnrs.biendata.org/). The API seems to work but the backend database not. Let's give them some time to recover :-)

**Comment by h-a-graham** [comment]
seems to be working again now...

**Comment by billy34** [comment]
Yes you are right. Closing issue for now.
